# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



def fibonacci(sequence):
    if sum((sequence[-2], sequence[-1])) > 4000000:
        return sequence
    else:
        sequence.append(sum((sequence[-2], sequence[-1])))
        return fibonacci(sequence)


def filter_series(series, cond):
    s = []
    for item in series:
        if cond(item):
            s.append(item)
    return s
  
            
def even(item):
    if item % 2 == 0:
        return True
    else:
        return False
    


print(sum(filter_series(fibonacci([1, 2]), even)))

